# This is a simple workflow to deploy a CDK stack

name: Deploy CDK Stack

on:
  push:
    branches: [ "main" ]

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  CHAINOFTRUST_DS_RECORD: ${{ secrets.CHAINOFTRUST_DS_RECORD }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install Python dependencies and CDK
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install -g aws-cdk

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Synth
      run: |
        cdk synth

    - name: Deploy
      run: |
        cdk deploy --require-approval never